# Generated by Django 3.0.7 on 2020-06-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel_data', '0002_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('purpose', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
