# Generated by Django 3.0.7 on 2020-06-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel_data', '0005_auto_20200610_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_travel_data.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='contribute',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Exeption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('expence', models.ManyToManyField(to='web_travel_data.Expence')),
                ('member', models.ManyToManyField(to='web_travel_data.Member')),
            ],
        ),
    ]
