# Generated by Django 3.0.7 on 2020-06-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel_data', '0006_auto_20200611_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='exeption',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
