# Generated by Django 3.0.7 on 2020-06-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel_data', '0008_remove_exeption_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='exeption',
            name='expences',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
