# Generated by Django 3.0.7 on 2020-06-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel_data', '0009_exeption_expences'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='return_to_close',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
