# Generated by Django 3.0.7 on 2020-06-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel_data', '0016_contribution_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='expence',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
