# Generated by Django 3.0.7 on 2020-06-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel_data', '0017_expence_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='expence',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
    ]
