# Generated by Django 3.0.7 on 2020-06-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel_data', '0018_auto_20200618_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expence',
            name='i',
            field=models.IntegerField(default=0),
        ),
    ]
