# Generated by Django 3.0.7 on 2020-06-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel_data', '0019_auto_20200618_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='i',
        ),
        migrations.RemoveField(
            model_name='exeption',
            name='i',
        ),
        migrations.RemoveField(
            model_name='expence',
            name='i',
        ),
        migrations.RemoveField(
            model_name='member',
            name='i',
        ),
    ]
