# Generated by Django 3.0.7 on 2020-06-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel_data', '0020_auto_20200620_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='exeption',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
    ]
