# Generated by Django 3.0.7 on 2020-06-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel_data', '0022_auto_20200621_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='compensator',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
