# Generated by Django 3.0.7 on 2020-06-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel_data', '0023_member_compensator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='compensator',
        ),
    ]
