# Generated by Django 3.0.7 on 2020-06-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel_data', '0026_remove_member_compensator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_travel_data.Member'),
        ),
    ]
