# Generated by Django 3.0.7 on 2020-06-25 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_travel_data', '0028_auto_20200625_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='team',
        ),
        migrations.RemoveField(
            model_name='exeption',
            name='team',
        ),
        migrations.RemoveField(
            model_name='expence',
            name='team',
        ),
        migrations.RemoveField(
            model_name='member',
            name='team',
        ),
        migrations.AddField(
            model_name='contribution',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exeption',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expence',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
