# Generated by Django 3.0.7 on 2020-06-25 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_travel_data', '0029_auto_20200625_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='exeption',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='expence',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='member',
            name='owner',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contribution',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web_travel_data.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exeption',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web_travel_data.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expence',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web_travel_data.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web_travel_data.Team'),
            preserve_default=False,
        ),
    ]
