# Generated by Django 3.0.7 on 2020-06-25 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel_data', '0032_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_travel_data.Team'),
        ),
        migrations.AlterField(
            model_name='exeption',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_travel_data.Team'),
        ),
        migrations.AlterField(
            model_name='expence',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_travel_data.Team'),
        ),
        migrations.AlterField(
            model_name='member',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_travel_data.Team'),
        ),
    ]
