# Generated by Django 3.0.7 on 2020-06-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel_data', '0034_auto_20200625_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
